### PR TITLE
Separate source and build directories

### LINKED ISSUE #33: Source directory and destination directory cannot be identical
https://github.com/dusktreader/sphinx-view/blob/28770b984f7270de287b9d16c42c45e06a769108/sview/builder.py#L213

https://github.com/sphinx-doc/sphinx/blob/dc0120be358de037daf7d76d8b8bc218a089d1b0/sphinx/application.py#L159

### PR DESCRIPTION
**Pull request by jougs**
Fixes #33.

### CODE REVIEW

**Comment by dusktreader** [comment]
Looks like there are unit test failures in the travis build

**Comment by jougs** [comment]
I'm working on it. Sorry for the noise.

**Comment by dusktreader** [comment]
Oh, no problem! Mostly just letting you know I saw the pull-request

**Comment by jougs** [comment]
@dusktreader: I just had another look, but can't really see why the test is failing. I'm afraid I can't invest more time into this and have to give up. Feel free to take my branch and integrate whatever you can use of it. I'm now closing this.

**Pull request closed without merging**
