### PR TITLE
Allow a specific sphinx conf.py to be used.

### PR DESCRIPTION
**Pull request by jsivak**
This PR added a command-line arg named "--config"  that accepts a sphinx conf.py file.

The expectation is that sphinx-view is run inside a virtual environment for a project that already has sphinx installed and configured. This allows sphinx-view to use any sphinx extensions that have been installed and configured in the virtual environment.

If sphinx-view is being used "outside" of a project's virtual environment, then extension support may be unpredictable or broken. Let me know if you have ideas or a point of view on how you want to approach this situation. (I *always* use sphinx-view in the same VE as the project docs)

### CODE REVIEW

**Comment by dusktreader** [comment]
The final change looks just fine.

As for how to handle running sphinx-view outside a virtualenv where extensions may not be installed, I'm not concerned about the app actually handling that. Instead, I'd prefer that such a warning be added to the documentation and usage for the executable.

Since sphinx-view is intended to be a tool for helping during development, I don't want to add a lot of extra code to support specific extensions or handle checking that all named extensions are available. Better to let the docs explain that if you want to do something fancy, you'll have to handle it in your sphinx config file, or better yet, just use sphinx-view to give you a flavor of your sphinx docs while understanding that they might not perfectly mirror a full build that you might get on, say, readthedocs.org

One final request: could you please squash the commits to one?

Again, thanks for the contribution

**Comment by jsivak** [comment]
I've not had much practice squashing commits.. I'll give it a shot. I'll see what I can do with the docs as well.

**Comment by dusktreader** [comment]
@jsivak I can do the squash if you like. Let me know if you've already done this, otherwise, I'll squash and merge

**Comment by jsivak** [comment]
I'm working on it today.. it will be good practice.. ;)

**Comment by jsivak** [comment]
Rebasing/squashing from my develop branch isn't working that well, so I'll create a new, "cleaner" pull request.

**Pull request closed without merging**
